services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwerty123
    networks:
      api_network: null
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  api_network: null

volumes:
  postgres: null