log_level: "debug"
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 30s
database:
  host: "localhost"
  port: 5432
  db_name: "bot"
  user: "postgres"
  password:
telegram_bot:
  token: 