// Code generated by MockGen. DO NOT EDIT.
// Source: company.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/testit-tms/webhook-bot/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockcompanyStorage is a mock of companyStorage interface.
type MockcompanyStorage struct {
	ctrl     *gomock.Controller
	recorder *MockcompanyStorageMockRecorder
}

// MockcompanyStorageMockRecorder is the mock recorder for MockcompanyStorage.
type MockcompanyStorageMockRecorder struct {
	mock *MockcompanyStorage
}

// NewMockcompanyStorage creates a new mock instance.
func NewMockcompanyStorage(ctrl *gomock.Controller) *MockcompanyStorage {
	mock := &MockcompanyStorage{ctrl: ctrl}
	mock.recorder = &MockcompanyStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompanyStorage) EXPECT() *MockcompanyStorageMockRecorder {
	return m.recorder
}

// GetCompanyByOwnerTelegramId mocks base method.
func (m *MockcompanyStorage) GetCompanyByOwnerTelegramId(ctx context.Context, ownerId int64) (entities.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyByOwnerTelegramId", ctx, ownerId)
	ret0, _ := ret[0].(entities.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyByOwnerTelegramId indicates an expected call of GetCompanyByOwnerTelegramId.
func (mr *MockcompanyStorageMockRecorder) GetCompanyByOwnerTelegramId(ctx, ownerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyByOwnerTelegramId", reflect.TypeOf((*MockcompanyStorage)(nil).GetCompanyByOwnerTelegramId), ctx, ownerId)
}

// UpdateToken mocks base method.
func (m *MockcompanyStorage) UpdateToken(ctx context.Context, companyId int64, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateToken", ctx, companyId, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateToken indicates an expected call of UpdateToken.
func (mr *MockcompanyStorageMockRecorder) UpdateToken(ctx, companyId, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateToken", reflect.TypeOf((*MockcompanyStorage)(nil).UpdateToken), ctx, companyId, token)
}

// MockchatStorage is a mock of chatStorage interface.
type MockchatStorage struct {
	ctrl     *gomock.Controller
	recorder *MockchatStorageMockRecorder
}

// MockchatStorageMockRecorder is the mock recorder for MockchatStorage.
type MockchatStorageMockRecorder struct {
	mock *MockchatStorage
}

// NewMockchatStorage creates a new mock instance.
func NewMockchatStorage(ctrl *gomock.Controller) *MockchatStorage {
	mock := &MockchatStorage{ctrl: ctrl}
	mock.recorder = &MockchatStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchatStorage) EXPECT() *MockchatStorageMockRecorder {
	return m.recorder
}

// GetChatsByCompanyId mocks base method.
func (m *MockchatStorage) GetChatsByCompanyId(ctx context.Context, id int64) ([]entities.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatsByCompanyId", ctx, id)
	ret0, _ := ret[0].([]entities.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatsByCompanyId indicates an expected call of GetChatsByCompanyId.
func (mr *MockchatStorageMockRecorder) GetChatsByCompanyId(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatsByCompanyId", reflect.TypeOf((*MockchatStorage)(nil).GetChatsByCompanyId), ctx, id)
}
