# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: pr
    - name: Checkout base code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.base.sha }}
        path: base

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Count lines of code
      id: loc
      run: |
        curl -sLO https://github.com/vearutop/sccdiff/releases/download/v1.0.3/linux_amd64.tar.gz && tar xf linux_amd64.tar.gz
        sccdiff_hash=$(git hash-object ./sccdiff)
        [ "$sccdiff_hash" == "ae8a07b687bd3dba60861584efe724351aa7ff63" ] || (echo "::error::unexpected hash for sccdiff, possible tampering: $sccdiff_hash" && exit 1)
        OUTPUT=$(cd pr && ../sccdiff -basedir ../base)
        echo "${OUTPUT}"
        echo "diff<<EOF" >> $GITHUB_OUTPUT && echo "$OUTPUT" >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT

    - name: Comment lines of code
      continue-on-error: true
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        header: LOC
        message: |
          ### Lines Of Code

          ${{ steps.loc.outputs.diff }}

    - name: Build
      working-directory: ./pr
      run: go build -v ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: ./pr

    - name: Test
      working-directory: ./pr
      run: go test -v ./... -coverprofile=./cover.out
    
    - name: check test coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        profile: cover.out
        local-prefix: github.com/testit-tms/webhook-bot
        threshold-file: 80
        threshold-package: 80
        threshold-total: 95 
